"""create tasting_note table and FK

Revision ID: a2e0a85c8a5e
Revises: 
Create Date: 2026-01-01 23:15:00.152262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e0a85c8a5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sool_id', sa.Integer(), nullable=False),
    sa.Column('aroma', sa.Float(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=True),
    sa.Column('acidity', sa.Float(), nullable=True),
    sa.Column('body', sa.Float(), nullable=True),
    sa.Column('finish', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sool_id'], ['sool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasting_notes_id'), 'tasting_notes', ['id'], unique=False)
    op.drop_index(op.f('ix_tasting_id'), table_name='tasting')
    op.drop_table('tasting')
    op.drop_index(op.f('ix_tasting_note_id'), table_name='tasting_note')
    op.drop_table('tasting_note')
    op.alter_column('reviews', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sool', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sool', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('tasting_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sool_id', sa.INTEGER(), nullable=False),
    sa.Column('aroma', sa.FLOAT(), nullable=True),
    sa.Column('sweetness', sa.FLOAT(), nullable=True),
    sa.Column('acidity', sa.FLOAT(), nullable=True),
    sa.Column('body', sa.FLOAT(), nullable=True),
    sa.Column('finish', sa.FLOAT(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['sool_id'], ['sool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasting_note_id'), 'tasting_note', ['id'], unique=False)
    op.create_table('tasting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sool_id', sa.INTEGER(), nullable=True),
    sa.Column('sweetness', sa.FLOAT(), nullable=True),
    sa.Column('acidity', sa.FLOAT(), nullable=True),
    sa.Column('body', sa.FLOAT(), nullable=True),
    sa.Column('aroma', sa.FLOAT(), nullable=True),
    sa.Column('aftertaste', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['sool_id'], ['sool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasting_id'), 'tasting', ['id'], unique=False)
    op.drop_index(op.f('ix_tasting_notes_id'), table_name='tasting_notes')
    op.drop_table('tasting_notes')
    # ### end Alembic commands ###
